image: tmaier/docker-compose:latest

variables:
  DOCKER_DRIVER: overlay2
  DEFAULT_RELEASE_VERSION: prerelease
  RELEASE_VERSION: prerelease

services:
  - docker:dind

before_script:
  - docker load -i ui-components.tar || true

stages:
  - prepare
  - install
  - test
  - build
  - deploy

prepare-image:
  stage: prepare
  script:
    - docker build -t ui-components .
    - docker save -o ui-components.tar ui-components
  artifacts:
    paths:
      - ui-components.tar

install-package:
  stage: install
  script:
    - docker-compose run --rm gitlab-ci /bin/sh -c
      "
        yarn install --frozen-lockfile --network-concurrency 1 &&
        npm rebuild node-sass
      "
  artifacts:
    paths:
      - node_modules/

lint:
  stage: test
  script:
    - docker-compose run --rm gitlab-ci yarn lint

test:
  stage: test
  script:
    - docker-compose run --rm gitlab-ci yarn test

build-bundle:
  stage: build
  script:
    - docker-compose run --rm gitlab-ci yarn build
  artifacts:
    paths:
      - es/
      - dist/
  only:
    refs:
      - master

build-styleguide:
  stage: build
  script:
    - docker-compose run --rm gitlab-ci yarn styleguide:build
  artifacts:
    paths:
      - styleguide/
  only:
    refs:
      - master

pages:
  stage: deploy
  dependencies:
    - build-styleguide
  script:
    - mkdir public
    - cp -r styleguide/* public
  artifacts:
    paths:
      - public
  only:
    refs:
      - master

deploy-npm:
  stage: deploy
  dependencies:
    - prepare-image
    - build-bundle
  script:
    - docker-compose run --rm gitlab-ci ./docker/bin/deploy-npm
  only:
    refs:
      - master
