image: tmaier/docker-compose:latest

variables:
  DOCKER_DRIVER: overlay2
  RELEASE_VERSION: patch

services:
  - docker:dind

before_script:
  - docker load -i ui-components.tar || true

stages:
  - prepare
  - install
  - test
  - build
  - deploy

prepare-image:
  stage: prepare
  script:
    - docker build -t ui-components .
    - docker save -o ui-components.tar ui-components
  artifacts:
    paths:
      - ui-components.tar

install-package:
  stage: install
  script:
    - docker-compose run -v ./node_modules:/code/node_modules --rm gitlab-ci /bin/sh -c
      "
        yarn install --frozen-lockfile &&
        npm rebuild node-sass
      "
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  script:
    - docker-compose run -v ./node_modules:/code/node_modules --rm gitlab-ci yarn test

build-bundle:
  stage: build
  script:
    - docker-compose run -v ./es:/code/es -v ./dist:/code/dist --rm gitlab-ci yarn build
  artifacts:
    paths:
      - es/
      - dist/
  only:
    refs:
      - master

build-styleguide:
  stage: build
  script:
    - docker-compose run -v ./styleguide:/code/styleguide --rm gitlab-ci yarn styleguide:build
  artifacts:
    paths:
      - styleguide/
  only:
    refs:
      - master

pages:
  stage: deploy
  dependencies:
    - build-styleguide
  script:
    - mkdir public
    - cp -r styleguide/* public
  artifacts:
    paths:
      - public
  only:
    refs:
      - master

deploy-npm:
  stage: deploy
  dependencies:
    - prepare-image
    - build-bundle
  script:
    - docker-compose run gitlab-ci /bin/sh -c
      "
        git config user.email 'continuous.integration@intellihr.com.au' &&
        git config user.name 'IntelliHR CI' &&
        echo '//registry.npmjs.org/:_authToken=$NPM_TOKEN' > .npmrc &&
        npm version $RELEASE_VERSION -m '[skip ci] Upgrade to %s' &&
        npm publish --access public &&
        git push https://$GIT_USERNAME:$GIT_TOKEN@gitlab.com/intellihr/ui-components.git HEAD:master
      "
  only:
    refs:
      - master
