version: '3'
services:
  gitlab-ci:
    image: ui-components:latest
    volumes:
      - ./node_modules:/code/node_modules
    environment:
      - RELEASE_VERSION=${RELEASE_VERSION}
      - NPM_TOKEN=${NPM_TOKEN}
      - GIT_USERNAME=${GIT_USERNAME}
      - GIT_TOKEN=${GIT_TOKEN}

  ui-components:
    build: .
    command: yarn styleguide
    ports:
      - 6060:6060
