version: '3'
services:
  local:
    build:
      context: .
      dockerfile: Dockerfile-local
    command: yarn styleguide
    ports:
      - 6060
    volumes:
      - ./src:/var/task/src:delegated
      - ./docs:/var/task/docs:delegated
      - ./dist:/var/task/dist:delegated
      - ./types:/var/task/types:delegated
      - node-cache:/var/task/node_modules/.cache

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile-jenkins

volumes:
  node-cache: ~
