version: '3'
services:
  gitlab-ci:
    image: ui-components:latest
    volumes:
      - .:/code
    environment:
      - DEFAULT_RELEASE_VERSION=${DEFAULT_RELEASE_VERSION}
      - RELEASE_VERSION=${RELEASE_VERSION}
      - NPM_TOKEN=${NPM_TOKEN}
      - GIT_USERNAME=${GIT_USERNAME}
      - GIT_TOKEN=${GIT_TOKEN}

  code: &code
    build: .
    volumes:
      - .:/code
    ports:
      - 6060:6060

  code-mac:
    <<: *code
    volumes:
      - .:/code
      - ui-components:/code/node_modules # Optimisation for Docker-Mac

volumes:
  ui-components: ~
