version: '3'
services:
  gitlab-ci:
    image: ui-components:latest
    volumes:
      - ./node_modules:/code/node_modules

  ui-components:
    build: .
    command: yarn styleguide
    ports:
      - 6060:6060
