version: '3'
services:
  gitlab-ci:
    image: ui-components:latest
    volumes:
      - .:/code
    environment:
      - DEFAULT_RELEASE_VERSION=${DEFAULT_RELEASE_VERSION}
      - RELEASE_VERSION=${RELEASE_VERSION}
      - NPM_TOKEN=${NPM_TOKEN}
      - GIT_USERNAME=${GIT_USERNAME}
      - GIT_TOKEN=${GIT_TOKEN}

  code:
    build: .
    volumes:
      - .:/code
      - ui-components:/code/node_modules # Optimisation for Docker-Mac
    ports:
      - 6060:6060

  review:
    build:
      context: .
      dockerfile: Dockerfile-review
    ports:
      - ${REVIEW_PORT-80}:80
    container_name: ${REVIEW_CONTAINER_NAME}

volumes:
  ui-components: ~
