version: '3'
services:
  local:
    build:
      context: .
      dockerfile: Dockerfile-local
    command: yarn styleguide
    ports:
      - 6060
    volumes:
      - .:/var/task:delegated
      - ui-components:/var/task/node_modules # Optimisation for Docker-Mac

volumes:
  ui-components: ~
