branch-defaults:
  review-app:
    environment: null
    group_suffix: null
deploy:
  artifact: styleguide.zip
global:
  application_name: ui-components
  branch: null
  default_ec2_keyname: null
  default_platform: docker-17.12.0-ce
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  repository: null
  sc: git
  workspace_type: Application
